# version: '2'
# services:
#   app1:
#     image: python_docker_jenkins:latest
#     ports:
#         - "3000"
#     # devices:
#     #   - '/dev/video0:/dev/video0'
#   nginx:
#     image: nginx:latest 
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     # depends_on:
#     #   - app 
#     ports:
#       - "80:80"
    
# docker run -u 0 --privileged --name jenkins -it -d -p 8080:8080 -p 50000:50000 -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):/usr/bin/docker -v /home/jenkins_home:/var/jenkins_home jenkins:test

version: "3"

services:
  app:
    build:
      context: app 
    ports:
      - "5000"

  nginx:
    image: nginx:latest 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app 
    ports:
      - "80:80"